// Generated by CoffeeScript 2.4.1
(function() {
  var add, d, i, s;

  i = 4;

  d = 4.0;

  s = "HackerRank ";

  add = function(i2, d2, s2) {
    console.log(i + i2);
    console.log((d + +d2).toFixed(1));
    return console.log(s + s2);
  };

  add(8, 4.0, "hello");

}).call(this);
