// Generated by CoffeeScript 2.4.1
(function() {
  var hello;

  hello = function(input) {
    console.log("Hello, World.");
    return console.log(input);
  };

  hello("some string");

}).call(this);
