// Generated by CoffeeScript 2.4.1
(function() {
  var operators;

  operators = function(meal_cost, tip_percent, tax_percent) {
    var tax, tip, totalCost;
    tip = meal_cost * tip_percent / 100;
    tax = meal_cost * tax_percent / 100;
    totalCost = meal_cost + tip + tax;
    return console.log(Math.round(totalCost));
  };

  operators(20, 20, 20);

}).call(this);
